version: '3.8'

services:
  api:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/photo_studio
      - BACKEND_CORS_ORIGINS=["http://localhost:5173"]
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=photo_studio
    ports:
      - "5432:5432"

volumes:
  postgres_data: 