[tool.poetry]
name = "backend"
version = "0.1.0"
description = "The backend for the photo studio booking application."
authors = ["Jules <jules@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiofiles = "24.1.0"
aiohappyeyeballs = "2.6.1"
aiohttp = "3.12.15"
aiohttp_socks = "0.10.1"
aioschedule = "0.5.2"
aiosignal = "1.4.0"
aiosqlite = "0.21.0"
alembic = "1.16.4"
"annotated-types" = "0.7.0"
anyio = "4.10.0"
arrow = "1.3.0"
"async-timeout" = "5.0.1"
asyncpg = "0.30.0"
attrs = "25.3.0"
babel = "2.17.0"
bcrypt = "4.3.0"
blinker = "1.9.0"
cachetools = "6.1.0"
certifi = "2025.8.3"
cffi = "1.17.1"
"charset-normalizer" = "3.4.3"
click = "8.1.7"
colorama = "0.4.6"
cryptography = "45.0.6"
distro = "1.9.0"
dnspython = "2.7.0"
ecdsa = "0.19.1"
"email_validator" = "2.2.0"
exceptiongroup = "1.3.0"
fastapi = "0.116.1"
"fastapi-cache2" = "0.2.2"
"fastapi-limiter" = "0.1.6"
frozenlist = "1.7.0"
greenlet = "3.2.4"
gunicorn = "23.0.0"
h11 = "0.16.0"
httpcore = "1.0.9"
httplib2 = "0.22.0"
httptools = "0.6.4"
httpx = "0.28.1"
ics = "0.7.2"
idna = "3.10"
iniconfig = "2.1.0"
itsdangerous = "2.2.0"
Jinja2 = "3.1.6"
jiter = "0.10.0"
"magic-filter" = "1.0.12"
Mako = "1.3.10"
MarkupSafe = "3.0.2"
marshmallow = "4.0.0"
multidict = "6.6.3"
oauthlib = "3.3.1"
openai = "1.99.6"
packaging = "25.0"
passlib = "1.7.4"
pendulum = "3.1.0"
pluggy = "1.6.0"
propcache = "0.3.2"
"proto-plus" = "1.26.1"
protobuf = "6.31.1"
"psycopg2-binary" = "2.9.10"
pyasn1 = "0.6.1"
"pyasn1_modules" = "0.4.2"
pycparser = "2.22"
pydantic = "2.11.7"
"pydantic-settings" = "2.10.1"
"pydantic_core" = "2.33.2"
pyparsing = "3.2.3"
"python-dateutil" = "2.9.0.post0"
"python-dotenv" = "1.1.1"
"python-jose" = "3.5.0"
"python-multipart" = "0.0.20"
"python-socks" = "2.7.2"
pytz = "2025.2"
PyYAML = "6.0.2"
redis = "6.4.0"
regex = "2025.7.34"
requests = "2.32.4"
"requests-oauthlib" = "2.0.0"
rsa = "4.9.1"
six = "1.17.0"
sniffio = "1.3.1"
SQLAlchemy = "2.0.42"
starlette = "0.47.2"
TatSu = "5.13.1"
tiktoken = "0.11.0"
tomli = "2.2.1"
tqdm = "4.67.1"
"types-python-dateutil" = "2.9.0.20250809"
"typing-inspection" = "0.4.1"
"typing_extensions" = "4.14.1"
tzdata = "2025.2"
uritemplate = "4.2.0"
urllib3 = "2.5.0"
uvicorn = "0.35.0"
uvloop = "0.21.0"
watchfiles = "1.1.0"
websockets = "15.0.1"
Werkzeug = "3.1.3"
yarl = "1.20.1"
YooMoney = "0.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
