# Template for secrets - DO NOT COMMIT TO VERSION CONTROL
# Create this file manually in production with real values

apiVersion: v1
kind: Secret
metadata:
  name: phstudio-secrets
  namespace: phstudio
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'your_password' | base64
  postgres_password: ""
  redis_password: ""
  secret_key: ""
  jwt_secret_key: ""
  grafana_password: ""